<div class="row" id="userRegForm">
	<div
		class="myBordersInset col-md-offset-3 col-xs-offset-3 col-sm-offset-3 col-md-6 col-sm-6 col-xs-6">
		<h3 class="text-center">Performance Evaluation Form</h3>

<?php
$form = $this->form;
$fields = $this->fields;
$form->prepare ();
$form->setAttribute ( 'method', 'post' );
$form->setAttribute ( 'class', 'form' );
$form->setAttribute ( 'role', 'form' );
$form->setAttribute ( 'autocomplete', 'off' );
echo $this->form ()->openTag ( $form );
foreach ( $fields as $label => $fieldName ) {
	$field = $form->get ( $fieldName );
	echo $this->formselect ( $field );
	echo $this->formElementErrors ( $field );
}
?>


	<?php
	$csrf = $form->get ( 'mcsrf' );
	echo $this->formhidden ( $csrf );
	echo $this->formElementErrors ( $csrf );
	
	?>
		

		<div class="form-group">
			<div class="control-group">
				<div class="controls">
					<button class="btn btn-primary btn-block">Save</button>
				</div>
			</div>
		</div>
		<?php
		echo $this->form ()->closeTag ();
		?>
		</div>

</div>
