<div class="row" id="userRegForm">
	<div
		class="myBordersInset col-md-offset-3 col-xs-offset-3 col-sm-offset-3 col-md-6 col-sm-6 col-xs-6">

<?php
$form = $this->form;
$form->prepare ();
$form->setAttribute ( 'method', 'post' );
$form->setAttribute ( 'class', 'form' );
$form->setAttribute ( 'role', 'form' );
$form->setAttribute ( 'autocomplete', 'off' );
echo $this->form ()->openTag ( $form );
?>

<?php

$fullName = $form->get ( 'fullName' );
echo $this->formtext ( $fullName );
echo $this->formelementerrors ( $fullName );
?>
<?php

$employeeCode = $form->get ( 'employeeCode' );
echo $this->forminput ( $employeeCode );
echo $this->formelementerrors ( $employeeCode );
?>
<?php

$loginId = $form->get ( 'loginId' );
echo $this->formtext ( $loginId );
echo $this->formelementerrors ( $loginId );
?>
						<?php
						$password = $form->get ( 'password' );
						echo $this->formpassword ( $password );
						echo $this->formelementerrors ( $password );
						?>
						<?php
						$passwordConfirm = $form->get ( 'passwordConfirm' );
						echo $this->formpassword ( $passwordConfirm );
						echo $this->formelementerrors ( $passwordConfirm );
						?>
<?php

						$personalEmailId = $form->get ( 'personalEmailId' );
						echo $this->formemail ( $personalEmailId );
						echo $this->formelementerrors ( $personalEmailId );
						?>

	<?php
	
	$mobile = $form->get ( 'mobile' );
	echo $this->formnumber ( $mobile );
	echo $this->formelementerrors ( $mobile );
	?>
		<?php
		$userIdParent = $form->get ( 'userIdParent' );
		echo $this->formselect ( $userIdParent );
		?>
	
<br> Birthday On:
		<div class="row">

			<div class="form-group column col-md-3 col-sm-3 col-xs-3">
			<?php
			$birthDay = $form->get ( 'birthDay' );
			echo $this->formselect ( $birthDay );
			
			?>
			</div>
			<div class="form-group column col-md-4 col-sm-4 col-xs-4"><?php
			
			$birthMonth = $form->get ( 'birthMonth' );
			echo $this->formselect ( $birthMonth );
			?>
			</div>
			<div class="form-group column col-md-5 col-sm-5 col-xs-5"><?php
			
			$birthYear = $form->get ( 'birthYear' );
			echo $this->forminput ( $birthYear );
			?>
			</div>
			<?php echo $this->formElementErrors($birthDay);?>
			<?php echo $this->formElementErrors($birthMonth);?>
			<?php echo $this->formElementErrors($birthYear);?>
			
</div>
	<?php
	$csrf = $form->get ( 'mcsrf' );
	echo $this->formhidden ( $csrf );
	echo $this->formElementErrors ( $csrf );
	
	?>
<?php

	$gender = $form->get ( 'gender' );
	echo $this->formselect ( $gender );
	echo $this->formelementerrors ( $gender );
	?>
		

		<div class="form-group">
			<div class="control-group">
				<div class="controls">
					<button class="btn btn-primary btn-block">Save</button>
				</div>
			</div>
		</div>
		<?php
		echo $this->form ()->closeTag ();
		?>
		</div>

</div>
