<?php
echo $this->headLink ()->prependStylesheet ( $this->basePath ( 'css/dataTables.bootstrap.min.css' ) )->prependStylesheet ( $this->basePath ( 'css/bootstrap.min.css' ) );
$allUSers = $this->allUsers;
?>
<table id="allUsersNode" class="table table-striped table-bordered"
	cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Full Name</th>
			<th>EmailId(Login Id)</th>
			<th>Access Level</th>
			<th>Created On</th>
			<th>Action</th>

		</tr>
	</thead>
	<tfoot>
		<tr>
			<th>Full Name</th>
			<th>EmailId(Login Id)</th>
			<th>Access Level</th>
			<th>Created On</th>
			<th>Action(Verify)</th>
		</tr>
	</tfoot>
	<tbody>
		
		<?php
		foreach ( $allUSers as $user ) {
			$status = $user ['accessLevel'];
			$userId = $user ['id'];
			if ($status == 0) {
				$class = "alert-danger";
				$status = 'DISABLED';
			} else {
				$status = 'ENABLED';
				$class = "alert-success";
			}
			?><tr id="<?php echo $userId;?>">
			<td class="oipuio <?php echo $class?>"
				id="<?php echo 'colX'.$userId;?>"><?php echo $userId;?></td>
			<td><?php echo $user['personalEmailId'];?></td>
			<td><?php echo $user['accessLevel'];?></td>
			<td><?php echo date('r',$user['createdOn']/1000);?></td>
			<td><button class="myBorders btn btn-xs btn-warning"
					onclick='updateUser22(<?php
			echo json_encode ( array (
					"colId" => 'colX' . $userId,
					"userId" => $userId,
					"action" => "disable" 
			) );
			?>)'>Mark Disabled</button>
				<button class="myBorders btn btn-xs btn-success"
					onclick='updateUser22(<?php
			echo json_encode ( array (
					"colId" => 'colX' . $userId,
					"userId" => $userId,
					"action" => "enable" 
			) );
			?>)'>Mark Enabled</button></td>

		</tr>
<?php }?>
	</tbody>
</table>
<?php
if (ENABLE_DATATABLES) {
	echo $this->headScript ()->prependFile ( $this->basePath ( 'js/dataTables.bootstrap.min.js' ) )->prependFile ( $this->basePath ( 'js/jquery.dataTables.min.js' ) );
	
	?>
<script type="text/javascript">
$(document).ready(function() {
    $('#allUsersNode').DataTable();
} );
</script>
<?php }?>
<script type="text/javascript">
var updateUser22= function(params){
	
	var obj = '#' + params['colId'];
	$(obj).removeClass("alert-warning");
	$(obj).addClass("alert-success");
	var userId = params['userId'];
	var action = params['action'];
	
	if(action=='enable'){
		status = 900;
	}
	if(action=='disable'){
		status = 800;
	}
$.ajax({
	url : '/admin/updateusers',
	type : "POST",
	dataType : 'json',
	data : {
		userId : userId,
		status : status
	},
	success : function(jStatus) {
		if (jStatus == 'Done') {
			console.log('message Sent');
		} 
	},
	error : function(response) {
		console.log(response);
	}
});
//window.parent.location = '/admin/listusers';
};
</script>
<style>
td.oipuio {
	color: #000000;
}
</style>