<?php
use Zend\Json\Json;

echo $this->headLink ()->prependStylesheet ( $this->basePath ( 'css/dataTables.bootstrap.min.css' ) )->prependStylesheet ( $this->basePath ( 'css/bootstrap.min.css' ) );
$allUSers = $this->data ['allUsers'];
?>
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">Employee Network</div>
		<div class="panel-body">
			<div class="treeview" id="abcd123456"></div>
		</div>
	</div>
</div>
<table id="allUsersNode" class="table table-striped table-bordered"
	cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Full Name</th>
			<th>EmailId(Login Id)</th>
			<th>Access Level</th>
			<th>Created On</th>

		</tr>
	</thead>
	<tfoot>
		<tr>
			<th>Full Name</th>
			<th>EmailId(Login Id)</th>
			<th>Access Level</th>
			<th>Created On</th>
		</tr>
	</tfoot>
	<tbody>
		<?php
		foreach ( $allUSers as $user ) {
			$status = $user ['accessLevel'];
			$userId = $user ['id'];
			if ($status == 0) {
				$class = "alert-danger";
				$status = 'DISABLED';
			} else {
				$status = 'ENABLED';
				$class = "alert-success";
			}
			?><tr id="<?php echo $userId;?>">
			<td class="oipuio <?php echo $class?>"
				id="<?php echo 'colX'.$userId;?>"><?php echo $userId;?></td>
			<td><?php echo $user['personalEmailId'];?>&nbsp;<a
				href="/admin/updateuser/<?php echo $userId?>"><i
					class="fa fa-pencil-square-o"></i></a> <a
				href="/report/evaluationform/<?php echo $userId?>"><i
					class="fa fa-star"></i></a></td>
			<td><?php echo $user['accessLevel'];?></td>
			<td><?php echo date('r',$user['createdOn']/1000);?></td>


		</tr>
<?php }?>
	</tbody>
</table>
<?php
if (ENABLE_DATATABLES) {
	echo $this->headScript ()->prependFile ( $this->basePath ( 'js/dataTables.bootstrap.min.js' ) )->prependFile ( $this->basePath ( 'js/jquery.dataTables.min.js' ) );
	
	?>
<script type="text/javascript">

$(document).ready(function() {
    $('#allUsersNode').DataTable();
} );
</script>
<?php }?>
<script type="text/javascript">
var allData= <?php echo Json::encode($this->data)?>;
var allUserData = allData.allUsers;
var idNdHashReverse = allData.idNdHashReverse;
console.log(allData);
var stepLength =<?php echo STEP_LENGTH?>;
var findChildren= function(parentPath){
	var trueStepLength = Number(parentPath.length)+Number(stepLength)+1 ;
	var children={};
	var possibleChilds;
	var childPath;
	if(typeof allData.lengthIndexedArray[trueStepLength] === 'object'){
		possibleChilds= allData.lengthIndexedArray[trueStepLength];
		for ( var nodeiD in possibleChilds) {
			if (possibleChilds.hasOwnProperty(nodeiD)) {
				childPath = possibleChilds[nodeiD];
				childIndx = childPath.indexOf (parentPath);
				if (childIndx >= 0) {
					children [nodeiD] = childPath;
				}
			}
		}
	}
	return children;
};

var treeDiv = document.getElementById("abcd123456");
var pth;
var roots= allData.lengthIndexedArray[allData.minLength];
// email = allUserData[nodeiD]['personalEmailId'];
var createList = function (collection){
	var list='<ul>';
	var email;
	for ( var nodeiD in collection) {
		if (collection.hasOwnProperty(nodeiD)) {
			pth= collection[nodeiD];
			email = allUserData[nodeiD]['personalEmailId'];
			list = list+'<li href="#" id="'+pth+'">'+email+'('+nodeiD+')'+'</li>';
		}
		
	}
	list = list+'</ul>';
	return list;
};


console.log(createList(roots));
var tree = roots;
$('#abcd123456').append(createList(roots));
function traverseList(givenTree){
	for ( var nodeiD in givenTree) {
		if (givenTree.hasOwnProperty(nodeiD)) {
			if(typeof(givenTree[nodeiD]) == 'object'){
				traverseList(givenTree[nodeiD]);
			}else{
				$('#'+givenTree[nodeiD]).append(createList(findChildren(givenTree[nodeiD])));
				traverseList(findChildren(givenTree[nodeiD]));
			}
			
		}
		
	}
};
traverseList(tree);


var updateUser22= function(params){
	var obj = '#' + params['colId'];
	$(obj).removeClass("alert-warning");
	$(obj).addClass("alert-success");
	var userId = params['userId'];
	var action = params['action'];
	
	if(action=='enable'){
		status = 900;
	}
	if(action=='disable'){
		status = 800;
	}
$.ajax({
	url : '/admin/updateusers',
	type : "POST",
	dataType : 'json',
	data : {
		userId : userId,
		status : status
	},
	success : function(jStatus) {
		if (jStatus == 'Done') {
			console.log('message Sent');
		} 
	},
	error : function(response) {
		console.log(response);
	}
});
//window.parent.location = '/admin/listusers';
};
</script>
<style>
td.oipuio {
	color: #000000;
}

div.panel:first-child {
	margin-top: 20px;
}

div.treeview {
	min-width: 100px;
	min-height: 100px;
	max-height: 256px;
	overflow: auto;
	padding: 4px;
	margin-bottom: 20px;
	color: #369;
	border: solid 1px;
	border-radius: 4px;
}

div.treeview ul:first-child:before {
	display: none;
}

.treeview, .treeview ul {
	margin: 0;
	padding: 0;
	list-style: none;
	color: #369;
}

.treeview ul {
	margin-left: 1em;
	position: relative
}

.treeview ul ul {
	margin-left: .5em
}

.treeview ul:before {
	content: "";
	display: block;
	width: 0;
	position: absolute;
	top: 0;
	left: 0;
	border-left: 1px solid;
	bottom: 15px;
}

.treeview li {
	margin: 0;
	padding: 0 1em;
	line-height: 2em;
	font-weight: 700;
	position: relative
}

.treeview ul li:before {
	content: "";
	display: block;
	width: 10px;
	height: 0;
	border-top: 1px solid;
	margin-top: -1px;
	position: absolute;
	top: 1em;
	left: 0
}

.tree-indicator {
	margin-right: 5px;
	cursor: pointer;
}

.treeview li a {
	text-decoration: none;
	color: inherit;
	cursor: pointer;
}

.treeview li button, .treeview li button:active, .treeview li button:focus
	{
	text-decoration: none;
	color: inherit;
	border: none;
	background: transparent;
	margin: 0px 0px 0px 0px;
	padding: 0px 0px 0px 0px;
	outline: 0;
}
</style>
<script type="text/javascript">
$.fn.extend({
	treeview:	function() {
		return this.each(function() {
			var tree = $(this);
			
			tree.addClass('treeview-tree');
			tree.find('li').each(function() {
				var stick = $(this);
			});
			tree.find('li').has("ul").each(function () {
				var branch = $(this); 
				branch.prepend("<i class='tree-indicator glyphicon glyphicon-chevron-right'></i>");
				branch.addClass('tree-branch');
				branch.on('click', function (e) {
					if (this == e.target) {
						var icon = $(this).children('i:first');
						icon.toggleClass("glyphicon-chevron-down glyphicon-chevron-right");
						$(this).children().children().toggle();
					}
				})
				branch.children().children().toggle();
				branch.children('.tree-indicator, button, a').click(function(e) {
					branch.click();
					
					e.preventDefault();
				});
			});
		});
	}
});
$(window).on('load', function () {
	$('.treeview').each(function () {
		var tree = $(this);
		tree.treeview();
	})
})
</script>